const config = {
  // ЗАМЕНИТЕ ТОКЕН НИЖЕ НА НОВЫЙ ОТ QRYPT
  QRYPT_API_TOKEN:
    "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVhYWRlNzNlYmFjODRhNDI5Zjk0YmE3OGM4YTk4YmNlIn0.eyJleHAiOjE3ODQyODE0MzgsIm5iZiI6MTc1Mjc0NTQzOCwiaXNzIjoiQVVUSCIsImlhdCI6MTc1Mjc0NTQzOCwiZ3JwcyI6WyJQVUIiXSwiYXVkIjpbIlJQUyJdLCJybHMiOlsiUk5EVVNSIl0sImNpZCI6ImxPNDRvc2NINlVOeGtSMWZGY1daMiIsImR2YyI6ImY0NjNlNTk2NTdlMTQwYmJiMmI4ZmMxMmIwOTRiMDk4IiwianRpIjoiOTlhOTkxNzE0Mzk0NDNjOGIxM2M4OTRiNWNmNjA5NTIiLCJ0eXAiOjN9.1WvHjitpR22b1RRBfjhKGoxGa0JjGMh0BaBnWFMHtTNvt_BbE9HzofRpp6J7RKJqX1xZgxgitPsRRfSAPv7r6g",
  QRYPT_API_URL: "https://api-eus.qrypt.com/api/v1/quantum-entropy?size=1",
};

export default config;
